---
#- name: Move back mongod.conf
#  template: src=mongod_init.conf.j2 dest=/etc/mongod.conf owner=root group=root mode=0644

- name: create administrative user siteUserAdmin
  mongodb_user:
    database: admin
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    login_port: "{{ mongodb_conf_port }}"
  with_items:
    - {
      name: "{{ mongodb_user_admin_name }}",
      password: "{{ mongodb_user_admin_password }}",
      roles: "userAdminAnyDatabase"
      }

- name: create administrative user siteRootAdmin
  mongodb_user:
    database: admin
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    login_user: "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"
    login_port: "{{ mongodb_conf_port }}"
  with_items:
    - {
      name: "{{ mongodb_root_admin_name }}",
      password: "{{ mongodb_root_admin_password }}",
      roles: "root"
      }


- name: create normal users
  mongodb_user:
    database: "{{ item.database }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    #replica_set: "{{ mongodb_conf_replSet }}"
    login_user: "{{ mongodb_user_admin_name }}"
    login_password: "{{ mongodb_user_admin_password }}"
    login_port: "{{ mongodb_conf_port }}"
  with_items:
    - "{{ mongodb_users }}"
  when: setup_mongodb_users

- name: Restart mongodb service
  service: name={{ mongodb_daemon_name }} state=restarted
  when: mongodb_manage_service
